### ISSUE TITLE
Problems on running xdnwallet

### ISSUE THREAD

**Issue by solkmaaker** [DigitalNoteXDN/digitalnotewallet#6] opened 2018-06-18 18:40 UTC
Seems that version v1.0.15b-beta has some issues.
It compiles fine https://pastebin.com/raw/CwGTp2M6
But when i tried to run it without previously downloaded blockchain, result was:
`Segmentation fault`
When i downloaded blockchain from Gdrive, link provided from homepage, files dated 15 may, result was: https://pastebin.com/raw/nwbFDTmH
Same result was when i used blockchain that was downloaded using older client.
System used was:
`DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.1
DISTRIB_CODENAME=serena
DISTRIB_DESCRIPTION="Linux Mint 18.1 Serena"
NAME="Linux Mint"
VERSION="18.1 (Serena)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.1"
VERSION_ID="18.1"
VERSION_CODENAME=serena
UBUNTU_CODENAME=xenial`
Previous (old) versions of XDN wallet compiled on same system OK, and also run OK.
Any ideas?

**Comment by DrCryptoToad** [comment] 2018-06-19 00:36
I went ahead and got a fresh VM of Linux Mint 18.1 Serena installed and I was able to clone repos of both the CLI v5.0.1 and the GUI 1.0.15b, compile both and experiencing no issues.  Both compile and both run without error.  Do you receive the segmentation fault error at a certain block height while syncing or does it happen almost immediately after running the client?  It sounds like your blockchain db could be corrupted (althought unusual that our downloaded chain is causing the same error).  Try resyncing your blockchain from scratch.

**Comment by DrCryptoToad** [comment] 2018-06-19 04:08
Okay I can confirm that this issue existed before our updates...try compiling 1.0.13 from https://github.com/xdn-project/digitalnotewallet and you will get the same segmentation faults as well (I did when I just tried).  It will actually crash regardless of whether it is compiled by the QT creator or not. 
 I'm curious if this error is being caused by a specific QT version.

**Comment by solkmaaker** [comment] 2018-06-19 14:41
`o@U31-70 ~ $ qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu`
As i noticed, segmentation fault comes when there is no blockchain, and immediately after one node is connected, log:
2018-Jun-19 17:35:16.606505 INFO [Blockchain] Blockchain not loaded, generating genesis block.
2018-Jun-19 17:35:16.649646 INFO [Blockchain] Blockchain initialized. last block: 0, d2176.h9.m35.s16 time ago, current difficulty: 1
2018-Jun-19 17:35:17.126344 INFO [node_server] Binding on 0.0.0.0:42080
2018-Jun-19 17:35:17.126466 INFO [node_server] Net service binded on 0.0.0.0:42080
2018-Jun-19 17:35:17.126524 INFO [node_server] Attempting to add IGD port mapping.
2018-Jun-19 17:35:21.130937 INFO [node_server] No IGD was found.
2018-Jun-19 17:35:21.131103 INFO [node_server] Starting node_server
2018-Jun-19 17:35:41.890179 INFO [protocol] [128.0.24.119:42080 OUT] Sync data returned unknown top block: 0 -> 318663 [318663 blocks (885 days) behind] 
2018-Jun-19 17:35:41.890179 INFO [protocol] SYNCHRONIZATION started


Insn't that error, when blockchain exist, indicate that there is google sparsehash problem, rather than QT problem?

**Comment by skironDotNet** [comment] 2018-06-19 15:33
This is not an error

2018-Jun-19 17:35:41.890179 INFO [protocol] [128.0.24.119:42080 OUT] Sync data returned unknown top block: 0 -> 318663 [318663 blocks (885 days) behind]

This means the peer connected to doesn't give the block you need. This is normal and existed in older XDN client and in XMR.

Download last "original" client from https://github.com/xdn-project/digitalnote/releases and test. If you get any "fragmentation error" means your BC is corrupted, because this wallet works with correct BC

**Comment by solkmaaker** [comment] 2018-06-19 15:46
> As i noticed, segmentation fault comes **when there is no blockchain**, and immediately after one node is connected
But OK, testing, stand by...

**Comment by DrCryptoToad** [comment] 2018-06-19 16:01
We were able to compile a working GUI wallet with QT 5.11.0 on QT Creator (after making some basic dependency path adjustments that changed in this version of QT) and the client works fine but will show "segmentation fault" error after you close it.  It does not crash randomly though, so this is the most stable version that we have compiled and we will upload the binary to the git soon.  I do not know why the wallet is more stable when compiled via the QT Creator vs compiled manually.  If we compile on the same system one with QT Creator and one manually via the terminal the QT Creator build is almost always more stable.  This also applies to older versions (pre-2018) such as v1.0.13.  It is also interesting to note that compiling on Linux Mint 18.1 with QT Creator works great but the same compile with Ubuntu 16.04.4 LTS with the same QT Creator and QT version is unstable.

So it seems there is something going on between distros and maybe also between different versions of QT dependencies.  It would be worth trying to build with QT v5.4.1 to see if that solves the issue as I see that is what my old binary is compiled with (v1.0.12).  As of now, like I said, our most stable version is QT 5.11.0 compiled with QT Creator on Linux Mint 18.1 and we will probably add it to releases soon.

**Comment by DrCryptoToad** [comment] 2018-06-19 16:35
@solkmaaker thank you as well.  We hope to have the precompiled binary release up for Linux later this evening.  It ran overnight here with no issues syncing and it seems to be stable.

**Comment by solkmaaker** [comment] 2018-06-19 16:44
I have no idea, can i check it somehow? About dialog says it uses 5.5.1, but same does the compiled version.
(also i noted hat if i disconnect network, then program runs, as soon as i connect: segmentation fault)
Working wersion (deb package) is downloaded from https://github.com/xdn-project/digitalnote/releases

**Comment by DrCryptoToad** [comment] 2018-06-19 16:48
@solkmaaker Interesting yeah that is how you check it.  Ok thank you.

**Closed** 2018-06-25 18:04 UTC
